= We have a blog!

To all who come to his happy blog, welcome!

For just over 3 years, MouseGuests has shared our Disney obsession over social media outlets such as https://twitter.com/mouseguests[Twitter] and https://www.facebook.com/MouseGuests[Facebook]. But we've felt that sometimes those options were limited and we had more to say.

So today, just in time for our next trip to Walt Disney World, we're pleased to unveil our brand new blog! Here we'll share news, tips, tricks, trip reports, and anything else that we think our Disney-crazed readers will enjoy. We'll focus primarily on Disney vacations such as Walt Disney World, Disneyland, and the Disney Cruise Line, but might toss in other tidbits of Disney info from time to time.

On Disneyland's opening day in July 1955, there were a few hiccups and things didn't go as smoothly as Walt would have hoped. Likewise, we may have a few wrinkles to sort out over the next few weeks with regard to styling and layout; so please pardon our pixie dust as we are just getting started. But stick with us and we hope to put together a Disney-oriented blog that will a source of joy and inspiration to all who read it!
