= A few introductions are in order

After setting up this blog in December, we hopped on a plane and went to Disney World for a week. Then with the holidays and other activities consuming our time, we're just now getting around to writing our first real blog post. As is customary, we'll start by introducing ourselves and telling you a bit about how we became obsessed with Disney World and Disneyland. 

My name is Craig and I'll probably be the one writing most of the articles here. Raymie is my beautiful and amazing wife and she is largely responsible for our Disney obsession. When we got married back in 1998, I asked her where she'd like to go on our honeymoon and she said Disney World. Neither of us had ever been before, so why not? I took care of the plans and booked us a week at Disney's Dixie Landings Resort (now known as Port Orleans Riverside). It was an amazing trip! Even so, it'd be 10 years before we'd return...

Fast forward to 2008. By this time we had added Maisy and Madi, our two little princesses, to our family and decided to take them to Disney World. Maisy was 4 years old and Madi was 2. These ages were perfect for introducing them to Disney World and it was fun seeing it through their eyes. Of course, they were limited on what they could ride, so we spent a great deal of our time seeking out characters for photographs and autographs. Madi specifically wanted to meet Snow White so we went *everywhere* to find her. Sadly we never found her. But it was a great trip nonetheless.

Three years passed before our next trip. By fall of 2011, Maisy had started figure skating and was invited to compete in a national figure skating competition in San Diego. While we were in California, we decided to drive up to Anaheim and visit Disneyland for our very first time. At that time construction walls were still up in California Adventure for Carthay Circle and Cars Land, but still had tons of fun. I recall finding Disneyland Park to have a lot of charm and character as compared to the Magic Kingdom, even if smaller.

At this point our Disney obsession kicked into high gear with several trips in a row. I won't bore you with mini trip reports for each trip, but here's a summary of all of the Disney vacations we've taken thus far:

 * Dec 1998 : Walt Disney World (Dixie Landings)
 * Dec 2008 : Walt Disney World (Caribbean Beach Resort)
 * Aug 2011 : Disneyland (Good Neighbor Hotel)
 * Dec 2012 : Walt Disney World (Port Orleans Riverside)
 * Sep 2013 : Disneyland (Paradise Pier Hotel)
 * Dec 2013 : Walt Disney World (Port Orleans Riverside)
 * May 2014 : Walt Disney World (Port Orleans Riverside)
 * Jan 2015 : Walt Disney World (Art of Animation)
 * May 2015 : Disneyland (Grand Californian)
 * Dec 2015 : Walt Disney World (Beach Club)

And we're already planning for trips to Disney World this May and Disneyland in June!

Suffice it to say, we're obsessed. Along the way, I started posting to Twitter, Facebook, and Instagram as MouseGuests (please follow!). And Raymie has become a travel agent specializing in Disney Vacations, so if you need help planning your next Disney vacation, go https://www.facebook.com/smvbyraymie[follow her on Facebook] or mailto:raymie@simplymagicalvacations.com[send her an email]. We love talking about Disney World and Disneyland and these are our outlets for enjoying Disney while we're away from the parks.

To wrap up this introduction post, we thought we'd help you get to know us better by sharing some of our favorite things about Disney Parks. 

 * **Craig's Favorites**
 ** **Favorite park**: Disneyland, mostly because of the rich details and history and because it's the only park that Walt actually walked in.
 ** **Favorite attraction**: Even though I'm a thrill ride junkie, I can't get enough of the Haunted Mansion and enjoy the details and subtle humor. After that, I'm a big fan of Pirates of the Caribbean, the Jungle Cruise, Big Thunder Mountain, Tower of Terror, and Radiator Springs Racers.
 ** **Favorite show**: Paint the Night is amazing and my current favorite. That said, I thought that the original World of Color (not the current version, which I'm not much of a fan of) was the most incredible thing I've ever seen.
 ** **Favorite resort hotel**: Port Orleans Riverside, because it's where we stayed on our honeymoon and because it's easily one of the nicest moderate resorts on Disney property. And the fact that Yehaa Bob performs there cinches it for me.
 ** **Favorite restaurant**: It's a toss-up. I love the burgers at Beaches and Cream (Beach Club), the kjøttkaker at Akershus (Epcot), the never-ending skillet of meat at Whispering Canyon (Wilderness Lodge) and the Monte Cristo at Cafe Orleans (Disneyland). It's hard to decide between these. Honorable mention goes Be Our Guest (Magic Kingdom) and Liberty Tree Tavern (Magic Kingdom). 
 ** **Favorite snack**: Dole Whip. 'nuff said.
 ** **Favorite character**: I share a birthday with Donald Duck (June 9), so there's obviously a connection there. But when meeting the characters, it's hard to beat the interaction with Gaston and the Tremaine family.
 ** **Favorite movie**: The Jungle Book. It has great music, a good story, and it was the first Disney movie I ever saw in the theater (at a drive-in, no less).
 * **Raymie's Favorites**
 ** **Favorite park**: Disneyland Park, because of Fantasyland Theatre and ToonTown. She says it has more character and is really unique.
 ** **Favorite attraction**: Soarin' because the smells and sights and movement immerses you in flight.
 ** **Favorite show**: Fantasmic! Mickey's up on the mountain and then suddenly he's on the ground! It's really well done; it's amazing. Some imagination, huh!
 ** **Favorite resort hotel**: Beach Club
 ** **Favorite restaurant**: Cafe Orleans because of the pommes frites!
 ** **Favorite snack**: The gingerbread cupcake they had at Studio Catering Co. during Christmas.
 ** **Favorite character**: Mickey Mouse. Hello, the guy's hilarious!
 ** **Favorite movie**: Little Mermaid
 * **Maisy's Favorites**
 ** **Favorite park**: Disneyland Park. Or, as she refers to it "Magic Kingdom in Disneyland" because she understands that this is Walt Disney's original Magic Kingdom. (We've raised her right.)
 ** **Favorite attraction**: Seven Dwarfs Mine Train in the Magic Kingdom
 ** **Favorite show**: Disneyland's Fantasmic! She didn't offer a reason, but we all know it's because of the Peter Pan scene, the superior dragon, and the Mark Twain Riverboat.
 ** **Favorite resort hotel**: Beach Club
 ** **Favorite restaurant**: Be Our Guest in the Magic Kingdom. She enjoys the pasta there.
 ** **Favorite snack**: Churro. 
 ** **Favorite character**: Cinderella
 ** **Favorite movie**: Cinderella
 * **Madi's Favorites**
 ** **Favorite park**: Disney California Adventure because it has Cars Land. Also Magic Kingdom because it's fun and has more to do than the other parks.
 ** **Favorite attraction**: Seven Dwarfs Mine Train, Buzz Lightyear's Space Ranger Spin/Astroblasters, Toy Story Midway Mania
 ** **Favorite show**: Festival of the Lion King because, unlike Fantasmic or World of Color, you won't get wet and cold.
 ** **Favorite resort hotel**: Art of Animation
 ** **Favorite restaurant**: Chef Mickey's
 ** **Favorite snack**: Mickey Ice Cream Bar
 ** **Favorite character**: Pluto because he's a dog and she loves dogs
 ** **Favorite movie**: Bolt and Lady and the Tramp (because they have dogs)

And now that you know a little bit about us, tell us something about you. Leave a comment here to introduce yourself and tell us what some of your favorite Disney things are! And be sure to follow MouseGuests on Facebook[https://www.facebook.com/MouseGuests], Twitter[https://twitter.com/mouseguests], and/or Instagram[https://www.instagram.com/mouseguests/]!


