= These parks are made for walking
:hp-tags: Disney World, walking, trip report

I had big plans of posting a trip report from our December stay at Beach Club, but have since decided that such an article would be extremely long and could be summarized simply with "It was a lot of fun!". So instead of giving a play by play on everything we did and everything we ate, I thought it'd be more informative to share how much we walked.

Although busses, boats, and monorails are helpful to get you from your resort to the parks, it's up to you and your two feet to get you around once you arrive at a park. You may not realize it, but you can log a *lot* of miles visiting Disney World or Disneyland. I've heard various numbers regarding the average number of miles a person walks per day in Disney World, but certainly it will depend on the individual and what they do. In short, your mileage may vary.

I don't currently own a FitBit or other tracking device. Raymie got one for Christmas, but that was after our trip, so it was of no use at that time. But having recently discovered that the Health app on my iPhone can track the number of steps and miles walked in a day, I decided to keep tabs on how much I walked using that app. Here are the results, including a brief explanation of what we did to get those miles):

 * **Dec 15th** - 9.01 miles : We arrived mid-day and after a quick lunch at Beaches and Cream, we went to the Magic Kingdom, including an evening at Mickey's Very Merry Christmas Party.
 * ** Dec 16th** - 11.32 miles : We went back to the Magic Kingdom for the full day.
 * ** Dec 17th** - 8.97 miles : We spent the full day at Animal Kingdom and then went back to the resort after the park closed. We had planned to go see Yehaa Bob, but everyone was tired and just wanted to go back and rest. While everyone else rested, I walked over to Epcot (from Beach Club) to see and photograph Illuminations. This added a few steps, but I found a place to watch along the bridge between UK and France, so it didn't dramatically impact my miles.
 * ** Dec 18th** - 9.15 miles : We spent the full day in Hollywood Studios. We had planned to see the Osborne Lights after the first Fantasmic! show, but didn't realize that they shut them down early for Symphony in the Stars. This being the first night for Symphony in the Stars, the park was crazy busy, so we ended up just going back to the resort.
 * ** Dec 19th** - 12.4 miles : We started our day in Epcot, spending most of the morning and early afternoon in Future World, before making brief circle around World Showcase. Then we caught a boat over to Hollywood Studios to see the Osborne Lights. My family went back to the resort to rest while I stayed back around the center stage area to see the Symphony in the Stars fireworks.
 * ** Dec 20th** - 10.72 miles : We spent a full day in the Magic Kingdom, heading back only a little early to pack so we could leave the next day.
 * ** Dec 21st** - 6.62 miles : Our last day was spent in the Magic Kingdom. The pre-Christmas crowds were really out in force, so we were limited on how much we could get done. After a few hours, we called it done and went back to the resort and from there to the airport to head home.

In total, I walked 68.19 miles during that week-long trip, averaging 9.74 miles per day. 

Of course, I can't speak with any certainty to the accuracy of the iPhone Health app, so the actual miles may be different. I was concerned that bumpy rides would register false miles, so I tested it on the bus ride from Beach Club to Magic Kingdom and was surprised to find that it didn't register any additional steps while on the bus. Strangely, while standing perfectly still in line for Soarin', I noticed that it had registered a few dozen steps. So again, the numbers may not be entirely accurate.

I can't wait to do this again on our upcoming Disney World and Disneyland trips. This time I'll be sure to capture data from Raymie's FitBit as well as from my iPhone for comparison. It'll also be interesting to see if the average miles per day in Disneyland will be any different from Disney World.

One final thought: Because of all of the walking you'll do in Disney Parks, be sure to wear comfortable shoes. I won't recommend any specific shoe, because the shoe I've found to be most comfortable is a sandal (which is usually the worst choice for going to Disney). For some it may be good old fashioned tennis shoes. Or, if you've seen the episode of Modern Family where they go to Disneyland, it was Minnie slippers that suited Gloria's feet. Just be sure to find whatever shoes work best for you and to break them in good before going to the parks. 

How many miles have you logged when visiting Disney World or Disneyland? Leave a comment and let us know!

