= Mickey's Soundsational Parade Live Stream Event
:published_at: 2016-02-17
:hb-tags: News, Disneyland

_"Come on, everybody! Let's do this! Here we go!" - Mickey Mouse, Mickey's Soundsational Parade_

We're a fan of all of Disney's parades (with Paint the Night being the solid favorite), but we really enjoy Mickey's Soundsational Parade in Disneyland. We can't wait to see it again on our upcoming trip to Disneyland. This energetic parade features many Disney favorites such as Donald, Goofy, Mary Poppins and Bert, Ariel, Tiana, and (of course) Mickey Mouse in a musical celebration! 

Fortunately, we won't have to wait until our next trip to see it again. One week from today, on February 24th, the http://disneyparks.disney.go.com/blog/[Disney Parks Blog] will host a live streaming event featuring Mickey's Soundsational Parade from Disneyland!  

This is an incredibly fun parade with some fantastic music. We highly recommend that you set aside the time to catch this live streaming event. The parade is currently scheduled to step off at 4:15pm Pacific Time (7:15pm if you're on the east coast). 

Have you ever seen Mickey's Soundsational Parade? If so, leave a comment and let us know what you think about it! And, please come back here after the live streaming event and discuss the parade.
