= Star Wars Stage Show and New Fireworks coming to Hollywood Studios
:hp-tags: Disney World, Hollywood Studios, Star Wars

There's been an awakening. Have you felt it?

Disney's Hollywood Studios is about to awaken with all new Star Wars experiences! The https://disneyparks.disney.go.com/blog/2016/02/new-star-wars-nighttime-spectacular-announced-set-to-make-theme-park-history/[Disney Parks Blog] is reporting that starting April 4th, a new Star Wars stage show named "_Star Wars: A Galaxy Far, Far Away_" will debut at center stage in Disney's Hollywood Studios. That same day, Captain Phasma (from _The Force Awakens_) will lead several First Order stormtroopers on a march from the Star Wars Launch Bay to center stage.

Then later this summer, a new Star Wars fireworks show, "_Star Wars: A Galactic Spectacular_" will be shown nightly, combining fireworks, special effects, and video projection on the Chinese Theater. The show will include a tower of fire and spotlight beams that form lightsabers in the sky.

Having seen the amazing Star Wars-themed "_Symphony in the Stars_", both at Star Wars Weekends and the newer incarnation of the show that debuted in December, I can only imagine that the new show will be nothing short of jaw-dropping. And having seen the Star Wars segment of _World of Color_ in Disney California Adventure, I imagine the tower of fire being much like the huge fireballs shot during that show. This should be awesome!

What do you think of all of the Star Wars experiences that Disney is offering in Disney's Hollywood Studios in advance of the new Star Wars Land to be opened in a few years? Leave a comment and let's discuss!