= Toy Story Midway Mania closing March 15; Third track opening this summer
:hp-tags: Disney World, News



We're hearing that _Toy Story Midway Mania_ in Disney's Hollywood Studios is closing on March 15th so that work in the queue area may be completed for a third track to be open sometime this summer.

_Toy Story Midway Mania_ is one of the most popular attractions in not only Disney's Hollywood Studios, but in all of Walt Disney World. This blend of dark ride and video game put guest in front of 3D screens where they shoot balls, throw darts at balloons, and toss pies to earn points. 

The standby line for the attraction is almost always well over an hour and a half, in spite of the fact that it currently has two virtually identical tracks. The popularity of the attraction has prompted Disney to build a third track adjacent to the existing ride for additional capacity. With the third track construction nearing completion, the last step in the project is to rework the queue to accommodate the new track. A similar project is underway in Epcot to add a third theater to the popular _Soarin'_ attraction, which is currently closed and expected to open sometime this summer.

With _Toy Story Midway Mania_ closed for at least a couple of months, this leaves Disney's Hollywood Studios with one less attraction in a park that is already sparse with attractions. Guests visiting Disney's Hollywood Studios will still be able to ride _Star Tours_, _The Twilight Zone Tower of Terror_, _Rock 'n' Roller Coaster Starring Aerosmith_, and _The Great Movie Ride_, as well as take in some of the shows, the _Citizens of Hollywood_, and _Fantasmic!_ at night. And as was reported yesterday, all new _Star Wars_ fireworks and a _Star Wars_ stage show will fill in the void while _Toy Story Midway Mania_ is down.

Unfortunately, the timing of this closure is unfortunate for our next Walt Disney World trip. _Toy Story Midway Mania_ is a favorite of ours and we'll have to reevaluate our plans to see how they'll be affected.

What do you think about this news? Does the closure of _Toy Story Midway Mania_ make Disney's Hollywood Studios less important for your Disney vacation? Or do you welcome the new third track in hopes that it will make it possible for you to ride it more often without spending so much time in line? Leave a comment below and let us know.
