= Our thoughts on Wonderful World of Disney: Disneyland 60
:hp-tags: Disneyland, Review

Did you tune in to ABC last night to see _Wonderful World of Disney: Disneyland 60_? We sure did and it was, in a word, fantastic! I won't go over the whole show in detail, but instead will discuss a few hightlights and observations.

The show started out with Fallout Boy performing "I Wanna Be Like You" from Disney's _The Jungle Book_. I can't say that I'm a big fan of Fall Out Boy, but I am a fan of the song so I was skeptical that they'd pull it off to my satisfaction. They exceeded my expectations and did a fantastic job covering the song.

Sir Elton John's performance of "Circle of Life" was as great as you'd expect. I was not, however, excited about the new song "Wonderful Crazy Night". That's not to say it was a bad song. Just nothing amazing, aside from the fireworks that were the backdrop of the song.

Josh Gad's brief tour of Disneyland was a ton of fun. His energy, and of course his voice, made it feel as if you were watching Olaf (from _Frozen_) give a tour of Disneyland. 

Speaking of _Frozen_, Idina Menzel's performance of "Let it Go" in front of the water fountains in Disney California Adventure was good, but didn't seem to carry the same emotion as the original recording.

The highlight of the show, in our opinion, was when Dick Van Dyke took the stage at the end of the "Step in Time" dance performance to channel his Bert character from _Mary Poppins_. For a 90 year old man, he still has some amazing moves.

A lot of people probably tuned in to hear more about the new _Star Wars_ lands coming to _Disneyland_ and _Disney's Hollywood Studios_. Harrison Ford introduced this section which was full of new concept art, including a better idea of what the Millenium Falcon attraction will look like. There was also what appeared to be a dark ride, perhaps an interactive dark ride (like _Buzz Lightyear's Space Ranger Spin_) that puts you in the middle of a battle with stormtroopers. They also mentioned an upscale dining experience as part of the new land. It all looks amazing, but it will take me a few days to fully digest and analyze what I saw.

The two other highlights were the performance of music from Star Wars and Fantasia. Of course, the music was fantastic, the backdrops and video shown during these performances made it more than just a listening experience.

All in all, _Wonderful World of Disney_ was a fun review of Disney's movies, music, and of Disneyland itself. That said, there was very little Disneyland in a show that purports to be a celebrate of Disneyland's 60th anniversary. Most of the show took place outside of Disneyland. I was hoping to see more of the _Paint the Night Parade_ and _Disneyland Forever_, not to mention several of the iconic Disneyland attractions. At best, only about 25% of the show was about Disneyland. 

Nevertheless, it was well worth watching and if you've DVR'd it, then you will probably watch it over and over again. I know we will. If, however, you want to see more of Disneyland and Disney California Adventure, then I recommend that you visit the parks, as the show is a let-down in that regard. (Email raymie@simplymagicalvacations.com for free help in planning your trip to Disneyland or Disney World.)

What did you think of _Wonderful World of Disney: Disneyland 60_? Leave a comment below and let us know.
